// Builds the Apps Script HTML files from the web page sources.
//   index.html -> apps-script/Index.html  (page shell, pulls in Style and App)
//   style.css  -> apps-script/Style.html  (<style> … </style>)
//   app.js     -> apps-script/App.html    (<script> … </script>)
// Usage: node tools/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url);
const read = f => readFileSync(new URL(f, root), 'utf8');
const write = (f, text) => {
  writeFileSync(new URL(f, root), text);
  console.log('Wrote', f, text.length, 'bytes');
};
const NOTE = '<!-- Generated by tools/build.mjs from %s. Edit that file instead. -->\n';

const css = read('style.css');
const js = read('app.js');
if (/<\/script/i.test(js)) throw new Error('app.js must not contain "</script"');
if (/<\/style/i.test(css)) throw new Error('style.css must not contain "</style"');

const page = read('index.html');
const shell = page
  .replace('<link rel="stylesheet" href="style.css">', "<?!= include('Style'); ?>")
  .replace('<script src="app.js"></script>', "<?!= include('App'); ?>");
if (shell === page || shell.includes('style.css') || shell.includes('app.js')) throw new Error('index.html tags not found');

write('apps-script/Index.html', NOTE.replace('%s', 'index.html') + shell);
write('apps-script/Style.html', NOTE.replace('%s', 'style.css') + `<style>\n${css}</style>\n`);
write('apps-script/App.html', NOTE.replace('%s', 'app.js') + `<script>\n${js}</script>\n`);
