// Builds apps-script/Index.html (one file: page + style + script) for Google Apps Script.
// Usage: node tools/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url);
const read = f => readFileSync(new URL(f, root), 'utf8');
const css = read('style.css');
const js = read('app.js');
if (/<\/script/i.test(js)) throw new Error('app.js must not contain "</script"');

const html = read('index.html')
  .replace('<link rel="stylesheet" href="style.css">', () => `<style>\n${css}</style>`)
  .replace('<script src="app.js"></script>', () => `<script>\n${js}</script>`);
if (html.includes('href="style.css"') || html.includes('src="app.js"')) throw new Error('index.html tags not found');

writeFileSync(new URL('apps-script/Index.html', root), '<!-- Generated by tools/build.mjs. Edit app.js / style.css / index.html instead. -->\n' + html);
console.log('Wrote apps-script/Index.html', html.length, 'bytes');
